title: ISCAS VIS
author: VIS
description: Visual Analytics Group of SKLCS, ISCAS

highlighter: null
permalink: /:year/:month/:day/:title/

url: 
baseurl: 

sass:
  sass_dir: public/css
  style: :compressed
